# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af67fa19198689a4446fc50cedb80de54f6080e0918c98047d0244775cc9fad3c67332d094e0338552e04626a25d4e723c0fbdc0e56d57aec15c218f5864bf96

test:
  secret_key_base: 43b4e7af90ceee559468e2c79d8ad7fafc375cb8ebbad49be315a36fb5fed6db3a694cbc3befb24af384c58aa2b554de4d65ed1717748c80d13bdcc41b581f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
